Comment out AWS CLI configuration verification step in aws-inventory.yml

diff --git a/.github/workflows/aws-inventory.yml b/.github/workflows/aws-inventory.yml
--- a/.github/workflows/aws-inventory.yml
+++ b/.github/workflows/aws-inventory.yml
@@ -56,14 +56,14 @@ jobs:
             aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
             aws configure set region "$AWS_DEFAULT_REGION"
         
-        - name: Verify AWS CLI Configuration
-          env:
-            AWS_REGION: us-east-1  # Hardcoded region for testing
-          run: |
-            if ! aws sts get-caller-identity; then
-              echo "Failed to verify AWS credentials." >&2
-              exit 1
-            fi
+#        - name: Verify AWS CLI Configuration
+#          env:
+#            AWS_REGION: us-east-1  # Hardcoded region for testing
+#          run: |
+#            if ! aws sts get-caller-identity; then
+#              echo "Failed to verify AWS credentials." >&2
+#              exit 1
+#            fi
 
         - name: Run AWS Auto Inventory
           run: |
